[build]
  publish = "."
  command = "echo 'Building Inmobarco Property Template...' && node build-env.js && echo 'Build completed - Static site ready with environment variables'"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Static assets - serve files directly (NO redirects to functions)
# These rules must come BEFORE the catch-all redirect

# SSR redirects ONLY for HTML pages
[[redirects]]
  from = "/"
  to = "/.netlify/functions/hello"
  status = 200
  force = true

[[redirects]]
  from = "/index.html"
  to = "/.netlify/functions/hello"
  status = 200
  force = true

# Catch-all for HTML pages ONLY (exclude static assets)
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/hello"
  status = 200
  conditions = {path = "!/*.*"}

# Cache headers for Netlify Functions
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Cache-control = "public, max-age=300"
    x-content-type-options = "nosniff"
    x-prerendered = "netlify-function"

# Security and performance headers for all pages
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Type = "text/css; charset=utf-8"

[[headers]]
  for = "*.json"
  [headers.values]
    Cache-Control = "public, max-age=300"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=300"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
    Access-Control-Allow-Origin = "*"