[build]
  publish = "."
  command = "echo 'Building Inmobarco Property Template...' && node build-env.js && echo 'Build completed - Static site ready with environment variables'"

[build.environment]
  NODE_VERSION = "18"
  # Note: All environment variables must be configured in Netlify's environment variables section
  # Required variables:
  # - VITE_API_BASE_URL
  # - VITE_API_TOKEN  
  # - VITE_API_INSTANCE
  # - VITE_COMPANY_NAME
  # - VITE_COMPANY_PHONE
  # - VITE_COMPANY_EMAIL
  # - VITE_ENCRYPTION_KEY
  # - VITE_ENCRYPTION_SALT

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.json"
  [headers.values]
    Cache-Control = "public, max-age=300"
