[build]
  publish = "."
  command = "echo 'Building Inmobarco Property Template...' && node build-env.js && echo 'Build completed - Static site ready with environment variables'"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Static assets (high priority) - must come before catch-all
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/css/*"
  to = "/css/:splat"
  status = 200

[[redirects]]
  from = "/js/*"
  to = "/js/:splat"
  status = 200

[[redirects]]
  from = "/favicon.ico"
  to = "/favicon.ico"
  status = 200

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

# SSR redirects for root and index - CRITICAL FOR ROOT PATH
[[redirects]]
  from = "/"
  to = "/.netlify/functions/hello"
  status = 200

[[redirects]]
  from = "/index.html"
  to = "/.netlify/functions/hello"
  status = 200

# SSR redirects - catch everything else
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/hello"
  status = 200

# Cache headers for Netlify Functions
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Cache-control = "public, max-age=300"
    x-content-type-options = "nosniff"
    x-prerendered = "netlify-function"

# Security and performance headers for all pages
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "*.json"
  [headers.values]
    Cache-Control = "public, max-age=300"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=300"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
    Access-Control-Allow-Origin = "*"